-- Flyway Migration V001: Create all database tables
-- Description: Initial schema creation for UDV Corporate Social Network

-- Legal entities table
CREATE TABLE legal_entities (
    legal_entity_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Comments table
CREATE TABLE comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE,
    employee_id INTEGER,
    post_id INTEGER
);

-- Communities table
CREATE TABLE communities (
    community_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    creator_id INTEGER,
    CONSTRAINT communities_type_check CHECK (type IN ('open', 'closed'))
);

-- Community members table
CREATE TABLE community_members (
    role VARCHAR(255) NOT NULL,
    community_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    PRIMARY KEY (community_id, employee_id),
    CONSTRAINT community_members_role_check CHECK (role IN ('admin', 'member'))
);

-- Community membership requests table
CREATE TABLE community_membership_requests (
    request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_timestamp TIMESTAMP(6) WITHOUT TIME ZONE,
    request_timestamp TIMESTAMP(6) WITHOUT TIME ZONE,
    status VARCHAR(255) NOT NULL,
    approver_id INTEGER,
    community_id INTEGER,
    employee_id INTEGER,
    CONSTRAINT community_membership_requests_status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);

-- Departments table
CREATE TABLE departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    head_id INTEGER
);

-- Subdivisions table
CREATE TABLE subdivisions (
    subdivision_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    department_id INTEGER,
    head_id INTEGER
);

-- Education table
CREATE TABLE education (
    education_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree VARCHAR(255),
    end_year INTEGER,
    specialty VARCHAR(255),
    start_year INTEGER,
    university VARCHAR(255),
    employee_id INTEGER
);

-- Employees table (main table)
CREATE TABLE employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    mattermost VARCHAR(255),
    online_status BOOLEAN,
    password_hash VARCHAR(255) NOT NULL,
    photo_url VARCHAR(255),
    position VARCHAR(255),
    profile_level VARCHAR(255),
    role VARCHAR(255),
    telegram VARCHAR(255),
    work_status VARCHAR(255),
    workplace VARCHAR(255),
    department_id INTEGER,
    legal_entity_id INTEGER,
    subdivision_id INTEGER,
    supervisor_id INTEGER,
    CONSTRAINT employees_role_check CHECK (role IN ('employee', 'supervisor', 'admin')),
    CONSTRAINT employees_work_status_check CHECK (work_status IN ('in_office', 'remote', 'sick_leave', 'vacation'))
);

-- Employee profiles table
CREATE TABLE employee_profiles (
    employee_id INTEGER PRIMARY KEY,
    about_me VARCHAR(255),
    birthday DATE,
    city VARCHAR(255),
    employment_status VARCHAR(255),
    hobbies VARCHAR(255),
    status_comment VARCHAR(255),
    status_state VARCHAR(255),
    CONSTRAINT employee_profiles_employment_status_check CHECK (employment_status IN ('permanent', 'temporary'))
);

-- Employee projects table
CREATE TABLE employee_projects (
    employee_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    PRIMARY KEY (employee_id, project_id)
);

-- Skills table
CREATE TABLE skills (
    skill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255)
);

-- Employee skills table
CREATE TABLE employee_skills (
    confirmation_date DATE,
    confirmation_document_url VARCHAR(255),
    confirmation_method VARCHAR(255),
    confirmation_status VARCHAR(255),
    proficiency_level INTEGER,
    employee_id INTEGER NOT NULL,
    skill_id INTEGER NOT NULL,
    PRIMARY KEY (employee_id, skill_id),
    CONSTRAINT employee_skills_confirmation_method_check CHECK (confirmation_method IN ('certificate', 'interview', 'exam', 'diploma')),
    CONSTRAINT employee_skills_confirmation_status_check CHECK (confirmation_status IN ('unconfirmed', 'confirmed'))
);

-- Gratitude and achievements table
CREATE TABLE gratitude_achievements (
    ga_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_url VARCHAR(255),
    content VARCHAR(255),
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE,
    type VARCHAR(255) NOT NULL,
    receiver_id INTEGER,
    sender_id INTEGER,
    CONSTRAINT gratitude_achievements_type_check CHECK (type IN ('gratitude', 'achievement'))
);

-- Likes table
CREATE TABLE likes (
    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE,
    employee_id INTEGER,
    post_id INTEGER
);

-- Posts table
CREATE TABLE posts (
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    media_type VARCHAR(255),
    media_url VARCHAR(255),
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE,
    type VARCHAR(255) NOT NULL,
    community_id INTEGER,
    employee_id INTEGER,
    CONSTRAINT posts_type_check CHECK (type IN ('news', 'announcement', 'discussion'))
);

-- Projects table
CREATE TABLE projects (
    project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confluence_url VARCHAR(255),
    description VARCHAR(255),
    name VARCHAR(255) NOT NULL
);

-- Skill confirmation requests table
CREATE TABLE skill_confirmation_requests (
    request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_date DATE,
    requested_proficiency_level INTEGER,
    status VARCHAR(255) NOT NULL,
    approver_id INTEGER,
    employee_id INTEGER,
    skill_id INTEGER,
    created_date DATE NOT NULL,
    CONSTRAINT skill_confirmation_requests_status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);

-- Skill grade descriptions table
CREATE TABLE skill_grade_descriptions (
    grade INTEGER NOT NULL,
    description VARCHAR(255) NOT NULL,
    skill_id INTEGER NOT NULL,
    PRIMARY KEY (grade, skill_id)
);

-- Skill suggestions table
CREATE TABLE skill_suggestions (
    suggestion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_date DATE,
    skill_name VARCHAR(255) NOT NULL,
    skill_type VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    approved_by INTEGER,
    suggested_by INTEGER,
    CONSTRAINT skill_suggestions_status_check CHECK (status IN ('pending', 'approved', 'rejected'))
);
